travis:
  secure:
    BINSTAR_TOKEN: DGF0yFU2uzMzlPEzdoo+1F6Nch/+qfJq5Ob28LxVm3rInom6BNMHtbw8QP0DUzxNBAAgRQYb4aGROdqyjTjWc39Rj1YYz46oakBtZC+RmNih1KygbT6BPhmt7ZJN+ZEaHyJ5SLZRs7+PGENHZLrpdTn8QiRvjTLpq/0XfULEkO75baQS8hUdJK+BVG0KzEjfw02FZB6dkSDAUKl42Dlqo1B8jJwzHaz0ltDjItunX4fAbSF/GxScR1XW7C1kM1NukcodAnTzA8yOIdn5S/OArhq2HkcYpnUXAxXUQM3osRNJGzFpsiI2SzmSTZQzRPA3Msh4Cv4G1l/Uo/GMkFGESCPtNgiUfwUL0Oezn7kczMJYULIx0qI0VrKdGMDAbjadAB3rVL9wkttoGOpZ+pwu7UbFVWBZzjwrR0XGrQPHHNkbC8jeq2bNVwRfR46P5P7RWdhWdcTHjTa6OzoohpXzSs2NLHTkaUw0MFQW4Moju54pDTM0oRL8uVjhn1eEKWR0rSXrwvyUrIjaR3HHCxX6sQrxuntT1QrnyLB5yVeSG0IfNWoFPBPf4hGltFrFAN6HXBjByAiIOgXLdvgib+tnrIZbeWSZmV8vDhdFvnh102p6cEhsLx+eWjnE2BAgPJrPFCvHY48eVljvNzp1NvznWdb9bqO2AJPdrgFiI/R/yY4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
